// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using cs2_languageApp_api.Data;

#nullable disable

namespace cs2_languageApp_api.Migrations
{
    [DbContext(typeof(AppDBContext))]
    partial class AppDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("cs2_languageApp_api.Models.English", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Translation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Word")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("english");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Translation = "auto",
                            Word = "car"
                        },
                        new
                        {
                            Id = 2,
                            Translation = "kocka",
                            Word = "cube"
                        });
                });

            modelBuilder.Entity("cs2_languageApp_api.Models.German", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Translation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Word")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("german");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Translation = "hospital",
                            Word = "krankenwagen"
                        },
                        new
                        {
                            Id = 2,
                            Translation = "sister",
                            Word = "schwester"
                        });
                });

            modelBuilder.Entity("cs2_languageApp_api.Models.Hungarian", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Translation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Word")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("hungarian");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Translation = "sorry",
                            Word = "bocsanot"
                        },
                        new
                        {
                            Id = 2,
                            Translation = "hallo",
                            Word = "Szia"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
